version: "3.10"

services:

  clonebot:

    image: ghcr.io/missemily2022/clonebot:new

    container_name: clonebot

    environment:

      - API_ID=${API_ID}

      - API_HASH=${API_HASH}

      - TG_BOT_TOKEN=${TG_BOT_TOKEN} 

      - UPDATE_GROUP=${UPDATE_GROUP}

      - UPDATE_CHANNEL=${UPDATE_CHANNEL}

      - AUTH_USERS=${AUTH_USERS}

      - CHUNK_SIZE=${CHUNK_SIZE}


    ports:

      - ${PORT}:${PORT}

    restart: unless-stopped
